#!/bin/sh

. /etc/init.d

[ -f /usr/local/sbin/sdf_task1.sh ] || exit 0

case "$1" in

        start)
                echo "script is starting...."
                /usr/local/sbin/sdf_task1.sh &
                echo "--------------------"
                touch /var/lock/subsys/sdf_script
                ;;
        stop)
                echo -n "script is stopping"
                killall -q -9 sdf_task1.sh &
                rm -f /var/lock/subsys/sdf_script
                ;;
        status)
                status sdf_script
                ;;
        restart|reload)
                $0 stop
                $0 start
                ;;
        *)
                echo "start, stop, restart|reload, status"
                exit 1
esac

exit 0
